export const leadStatus = ['OPENED', 'CLOSED', 'WON', 'LOST']

export const leadStages = [
    'QUALIFIED', 'LEAD', 'MEETING', 
    'NEEDS-DETAILS', 'FOLLOW-UP', 'UNQUALIFIED',
    'NEGOTIATION', 'FREE-TRIAL', 'ONBOARDING'
]

export const MessagesTemplatesCategories = [
    'INTRODUCTION', 'EDUCATIONAL-CONTENT', 'THOUGHT-LEADERSHIP',
    'SERVICE-BENEFITS', 'CASE-STUDIES', 'COMPARISON-GUIDES',
    'PROMOTIONS', 'FREE-TRIALS', 'PERSONALIZED-RECOMMENDATIONS',
    'ONBOARDING-SUPPORT', 'UP-SELLING', 'CROSS-SELLING', 'CUSTOMER-SUCCESS-STORIES'
]

export const valuesEntity = ['LEADS', 'STAGES', 'MESSAGES']